apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: testnewproject
spec:
  template:
    metadata:
      labels:
        app: testnewproject
    spec:
      containers:
      - name: testnewproject
        image: dhineshk6/test:testnewproject
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
