apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testnewproject
  labels:
     app: testnewproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testnewproject
  template:
    metadata:
      labels:
        app: testnewproject
    spec:
      containers:
      - name: testnewproject
        image: dhineshk6/test:testnewproject
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
