node {
    docker.withRegistry('https://hub.docker.com/', 'docker-hub-credentials') {
    	def mvnHome
    	
    	stage('checkout'){
        
        mvnHome = tool 'M3'
        git url: 'https://github.com/dhineshk6/kub.git'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
        }
    
    dir('testocenewproject'){
        stage('build'){
	        sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean install"
	        sh 'docker login --username dhineshk6 --password Docker@1234'
	        sh ("docker build -t testocenewproject .")
	        sh ("docker tag  testocenewproject dhineshk6/test:testocenewproject")
	        sh ("docker push dhineshk6/test:testocenewproject")
    	}
    	
    	stage('create docker image'){
		        sh 'docker login --username dhineshk6 --password Docker@1234'
		        sh ("docker build -t address-rest-api .")
		        sh ("docker tag  address-rest-api dhineshk6/test:address-rest-api")
    	}
    	
    	stage('push docker image'){
			sh ("docker push dhineshk6/test:testocenewproject")
    	}
    	
    	stage('create deployment'){
    	    sh 'kubectl delete deployments testocenewprojectapi || true' 
	    sh 'kubectl create -f deployment.yaml --validate=false'
    	}
    	
    	stage('create service'){
	    sh 'kubectl delete services testocenewprojectapiservice || true'
	    sh 'kubectl create -f services.yaml --validate=false'
    	}
    }
    }
}
